<x-layouts.app title="Pengaturan Admin">
    <main class="container py-4">
        <div class="d-flex justify-content-between align-items-center mb-3"><div><div class="eyebrow">Admin</div><h1 class="fw-bold mb-0">Pengaturan Operasional</h1><p class="text-secondary mb-0">Atur area, promo, slot acara, dan jam operasional.</p></div><a href="{{ route('admin.dashboard') }}" class="btn btn-outline-secondary">Dashboard</a></div>
        <div class="row g-4">
            <div class="col-lg-6"><div class="soft rounded p-3"><h2 class="h5 fw-bold">Area Pengiriman</h2><form method="post" action="{{ route('admin.settings.areas') }}" class="row g-2 mb-3">@csrf<div class="col-6"><input name="district" class="form-control" placeholder="Kecamatan" required></div><div class="col-6"><input name="village" class="form-control" placeholder="Kelurahan" required></div><div class="col-6"><input name="delivery_fee" type="number" class="form-control" placeholder="Ongkir" required></div><div class="col-6"><input name="eta_minutes" type="number" class="form-control" placeholder="ETA menit" required></div><div class="col-12"><button class="btn btn-tomato">Simpan Area</button></div></form>@foreach($areas as $area)<div class="d-flex justify-content-between border-top py-2 small"><span>{{ $area->district }} - {{ $area->village }}</span><strong>Rp{{ number_format($area->delivery_fee,0,',','.') }} · {{ $area->eta_minutes }}m</strong></div>@endforeach</div></div>
            <div class="col-lg-6"><div class="soft rounded p-3"><h2 class="h5 fw-bold">Voucher & Promo</h2><form method="post" action="{{ route('admin.settings.vouchers') }}" class="row g-2 mb-3">@csrf<div class="col-4"><input name="code" class="form-control" placeholder="Kode" required></div><div class="col-8"><input name="name" class="form-control" placeholder="Nama promo" required></div><div class="col-4"><select name="type" class="form-select"><option value="percent">%</option><option value="fixed">Nominal</option></select></div><div class="col-4"><input name="value" type="number" class="form-control" placeholder="Nilai" required></div><div class="col-4"><input name="minimum_spend" type="number" class="form-control" placeholder="Min belanja" required></div><div class="col-6"><input name="max_discount" type="number" class="form-control" placeholder="Maks diskon"></div><div class="col-6"><input name="expires_at" type="date" class="form-control"></div><div class="col-12"><button class="btn btn-tomato">Simpan Voucher</button></div></form>@foreach($vouchers as $voucher)<div class="d-flex justify-content-between border-top py-2 small"><span>{{ $voucher->code }} - {{ $voucher->name }}</span><strong>{{ $voucher->type === 'percent' ? $voucher->value.'%' : 'Rp'.number_format($voucher->value,0,',','.') }}</strong></div>@endforeach</div></div>
            <div class="col-lg-6"><div class="soft rounded p-3"><h2 class="h5 fw-bold">Slot Pengiriman</h2><form method="post" action="{{ route('admin.settings.slots') }}" class="row g-2 mb-3">@csrf<div class="col-4"><select name="day_of_week" class="form-select">@foreach(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'] as $day)<option>{{ $day }}</option>@endforeach</select></div><div class="col-3"><input name="starts_at" type="time" class="form-control" required></div><div class="col-3"><input name="ends_at" type="time" class="form-control" required></div><div class="col-2"><input name="max_orders" type="number" class="form-control" placeholder="Max" required></div><div class="col-12"><button class="btn btn-tomato">Simpan Slot</button></div></form>@foreach($slots->take(12) as $slot)<div class="d-flex justify-content-between border-top py-2 small"><span>{{ $slot->day_of_week }}</span><strong>{{ substr($slot->starts_at,0,5) }}-{{ substr($slot->ends_at,0,5) }} · {{ $slot->max_orders }}</strong></div>@endforeach</div></div>
            <div class="col-lg-6"><div class="soft rounded p-3"><h2 class="h5 fw-bold">Jam Operasional & Cut-off</h2><form method="post" action="{{ route('admin.settings.hours') }}" class="row g-2 mb-3">@csrf<div class="col-3"><select name="day_of_week" class="form-select">@foreach(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'] as $day)<option>{{ $day }}</option>@endforeach</select></div><div class="col-3"><input name="opens_at" type="time" class="form-control"></div><div class="col-3"><input name="closes_at" type="time" class="form-control"></div><div class="col-3"><input name="cutoff_at" type="time" class="form-control" value="20:00" required></div><div class="col-12"><button class="btn btn-tomato">Simpan Jam</button></div></form>@foreach($hours as $hour)<div class="d-flex justify-content-between border-top py-2 small"><span>{{ $hour->day_of_week }}</span><strong>{{ substr($hour->opens_at,0,5) }}-{{ substr($hour->closes_at,0,5) }} · cut-off {{ substr($hour->cutoff_at,0,5) }}</strong></div>@endforeach</div></div>
        </div>
    </main>
</x-layouts.app>
